apiVersion: v1
kind: Pod
metadata:
  name: duchy-computation-control-pod
  labels:
    app: duchy-computation-control-app
spec:
  containers:
    - name: duchy-computation-control-container
      image: bazel/src/main/kotlin/org/wfanet/measurement/service/internal/duchy/computationcontrol:computation_control_server_image
      imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: duchy-computation-control
spec:
  selector:
    app: duchy-computation-control-app
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: duchy-mill-pod
spec:
  containers:
    - name: duchy-mill-container
      image: bazel/src/main/kotlin/org/wfanet/measurement/service/internal/duchy/mill:mill_task_image
      imagePullPolicy: Never
      args: ["--next-worker=$(WORKER_SERVICE_SERVICE_HOST):$(WORKER_SERVICE_SERVICE_PORT)"]